# This script deploys your website automatically
name: Deploy to GitHub Pages

# Only trigger this script when you push to the main branch
on:
  push:
    branches: [ main ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our main branch
    steps:
    - uses: actions/checkout@v2

    # Run our deployment command
    - name: Deploying the static website to gh-pages
      run: npm run deploy
